#!/usr/bin/env bash

if [ -f /.dockerenv ]; then
    echo Docker 环境下不需要执行本命令，直接用 start-ui 即可启动。
    exit;
fi

TMP=$(which bash)
if [ "x$TMP" = "x" ]; then
    echo 本程序运行前需要先安装 bash/tmux，并编译 TinTin++。
    echo 请参考 README.md 指引进行安装。
    exit
fi

export SHELL=$TMP

TMP=$(which tmux)
if [ "x$TMP" = "x" ]; then
    echo 本程序运行前需要先安装 bash/tmux，并编译 TinTin++。
    echo 请参考 README.md 指引进行安装。
    exit
fi

if [ ! -x bin/tt++ ]; then
    echo 本程序运行前需要先安装 bash/tmux，并编译 TinTin++。
    echo 请参考 README.md 指引进行安装。
    exit
fi

export HOME=$(pwd)
export PATH=$HOME/bin:$PATH

TMUXCONFPATH="$HOME/var/tmux.conf"
if [ ! -f $TMUXCONFPATH ]; then
    TMUXCONFPATH="$HOME/tmux.conf"
fi

export TMUXCMD="tmux -L MUD -f $TMUXCONFPATH"

BASHPROFILE="$HOME/var/profile.sh"
if [ ! -f $BASHPROFILE ]; then
    BASHPROFILE="$HOME/profile.sh"
fi

rm -f .bash_profile
ln -s $BASHPROFILE .bash_profile

exec bash -l start-ui
