#!/usr/bin/env bash

TMP=$(which bash)
if [ "x$TMP" = "x" ]; then
    echo 本程序运行前需要先安装 bash/tmux，并编译 TinTin++。
    echo 请参考 README.md 指引进行安装。
    exit
fi

export SHELL=$TMP

TMP=$(which tmux)
if [ "x$TMP" = "x" ]; then
    echo 本程序运行前需要先安装 bash/tmux，并编译 TinTin++。
    echo 请参考 README.md 指引进行安装。
    exit
fi

if [ ! -x bin/tt++ ]; then
    echo 本程序运行前需要先安装 bash/tmux，并编译 TinTin++。
    echo 请参考 README.md 指引进行安装。
    exit
fi

export HOME=$(pwd)
export PATH=$HOME/bin:$PATH
export TMUXCMD="tmux -L MUD -f $HOME/tmux.conf"

test -f .bash_profile || ln -s profile.sh .bash_profile
exec bash -l
