#!/usr/bin/env sh

apt update
apt upgrade
apt reinstall readline bash
apt install git clang which make libgnutls pcre zlib git bash tmux ncurses-utils

if [ -d /data/data/com.termux/files/home/storage/shared/ ]; then
    mkdir /data/data/com.termux/files/home/storage/shared/my-paotin
    ln -s /data/data/com.termux/files/home/storage/shared/my-paotin ~/my-paotin
else
    mkdir ~/my-paotin
fi

mkdir -p ~/my-paotin/{ids,etc,data,log,plugins}

git clone https://github.com/mudclient/paotin
ln -s ~/my-paotin paotin/var
